//! Per-app writers.
//!
//! Every target follows the same contract so `theme apply` can never fight it:
//!
//! 1. The accent lives in its **own generated file**, never inside a themed
//!    file. `theme apply` overwrites themed files; it doesn't know about ours.
//! 2. The host config gets **one include line**, re-ensured on every run — so
//!    if a theme snapshot did clobber it, the next apply puts it back.
//! 3. Reloads are in-place signals (SIGUSR1/2, `makoctl reload`), never
//!    restarts, so recoloring doesn't flash the bar or drop terminals.
//!
//! mako is the exception: its config format has no include, so its colours are
//! patched between markers in the live config — which is exactly what
//! `theme apply` already does to that file.

use crate::ramp::Ramp;
use crate::source::home;
use std::io;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

pub const BEGIN: &str = "wallaccent:begin";
pub const END: &str = "wallaccent:end";

const HEADER: &str = "generated by wallaccent — edits are overwritten; see `wallaccent --help`";

/// What one target did, for the run report.
#[derive(Debug, Clone)]
pub struct Outcome {
    pub name: &'static str,
    pub changed: bool,
    pub note: String,
}

impl Outcome {
    fn done(name: &'static str, changed: bool, note: impl Into<String>) -> Self {
        Outcome {
            name,
            changed,
            note: note.into(),
        }
    }
}

/// Every target wallaccent knows how to recolor.
pub const ALL: &[&str] = &[
    "waybar",
    "kitty",
    "kde",
    "hyprland",
    "mako",
    "rofi",
    "fastfetch",
    "gtk",
    "rice",
];

/// Targets enabled unless the config says otherwise.  These are deliberately
/// the common desktop surfaces, not merely the bar accent: a new wallpaper
/// should also give Dolphin, Qt applications and terminal text a matching,
/// readable palette.
pub const DEFAULT_ON: &[&str] = &[
    "waybar",
    "kitty",
    "kde",
    "hyprland",
    "mako",
    "rofi",
    "fastfetch",
    "gtk",
    "rice",
];

/// Recolor one target. `ramp` of `None` means "stand down" — write inert
/// files so the theme's own colours show through again.
///
/// `smooth_from` carries the *previous* ramp while a smooth fade is running:
/// file-writers write the final colours immediately, live-writers (hyprland
/// borders) and the one target fastfetch owns get stepped separately so the
/// fade stays coherent.
pub fn apply(
    name: &str,
    ramp: Option<&Ramp>,
    smooth_from: Option<&Ramp>,
    dry: bool,
) -> io::Result<Outcome> {
    match name {
        "waybar" => waybar(ramp, smooth_from, dry),
        "kitty" => kitty(ramp, dry),
        "kde" => kde(ramp, dry),
        "hyprland" => hyprland(ramp, smooth_from, dry),
        "mako" => mako(ramp, dry),
        "rofi" => rofi(ramp, dry),
        "fastfetch" => fastfetch(ramp, smooth_from, dry),
        "gtk" => gtk(ramp, dry),
        "rice" => rice(ramp, dry),
        other => Ok(Outcome::done(
            "unknown",
            false,
            format!("no target '{other}'"),
        )),
    }
}

// ── waybar ─────────────────────────────────────────────────────────────────

fn waybar(ramp: Option<&Ramp>, smooth_from: Option<&Ramp>, dry: bool) -> io::Result<Outcome> {
    let css = match ramp {
        // Themes all route their highlight through @accent / @main-br, so
        // redefining those two after the theme is enough to recolor the bar.
        // During a smooth fade the file also carries a CSS `transition`: one
        // SIGUSR2 hot-swap then tweens every recolored element natively
        // (rewriting the CSS step-by-step loses frames to waybar's reload
        // debounce — that was the choppy fade).
        Some(r) => {
            let mut css = format!(
                "/* {HEADER} */\n\
                 @define-color accent   {};\n\
                 @define-color main-br  {};\n\
                 @define-color emberglow {};\n",
                Ramp::hex(r.accent),
                Ramp::hex(r.accent),
                Ramp::hex(r.accent_hi),
            );
            if smooth_from.is_some() {
                css.push('\n');
                css.push_str(crate::smooth::CSS_TRANSITION);
                css.push('\n');
            }
            css
        }
        None => format!("/* {HEADER} */\n/* inactive — theme colors in use */\n"),
    };
    let mut changed = write_if_changed(&home().join(".config/waybar/accent.css"), &css, dry)?;
    // The default bar pulls its palette from theme.css and its rules from
    // styles/*.css, so an import in between overrides cleanly.
    changed |= ensure_after(
        &home().join(".config/waybar/style.css"),
        "@import \"theme.css\";",
        "@import \"accent.css\";",
        dry,
    )?;

    // The winmode taskbar is self-contained: its own `win-*` palette, then its
    // rules. An import can't help (wrong names, and GTK resolves colors in
    // order), so the overrides go in a block right after that palette.
    //
    // The bar's own background is tinted too, not just its highlights — but
    // through `surface`, which holds the wallpaper's hue at the same near-black
    // value the themes ship, so the bar takes the colour without going light.
    // Alphas match the palette's (the bar is translucent over the wallpaper).
    let win = home().join(".config/waybar/windows/style.css");
    changed |= remove_line(&win, "@import \"accent.css\";", dry)?;
    let win_body = match ramp {
        Some(r) => {
            let c = Ramp::rgb_csv(r.accent);
            format!(
                "@define-color win-accent   {};\n\
                 @define-color win-accent2  {};\n\
                 @define-color win-bg       rgba({}, 0.94);\n\
                 @define-color win-menu-bg  rgba({}, 0.98);\n\
                 @define-color win-edge     rgba({c}, 0.16);\n\
                 @define-color win-hover    rgba({c}, 0.12);\n\
                 @define-color win-pill-bg  rgba({c}, 0.08);\n\
                 @define-color win-pill-br  rgba({c}, 0.18);\n\
                 @define-color win-menu-br  rgba({c}, 0.22);\n",
                Ramp::hex(r.accent),
                Ramp::hex(r.accent_hi),
                Ramp::rgb_csv(r.surface),
                Ramp::rgb_csv(r.surface_hi),
            )
        }
        None => String::new(),
    };
    changed |= patch_block(
        &win,
        &format!("/* {BEGIN} */"),
        &format!("/* {END} */"),
        &win_body,
        Anchor::AfterLastLineStartingWith("@define-color"),
        dry,
    )?;

    // SIGUSR2 = hot-swap the CSS in place (this waybar build is patched for
    // that; vanilla 0.15 would restart the process). During a smooth fade the
    // single swap is what kicks off the CSS transition — exactly one signal.
    if !dry && changed && running("waybar") {
        signal("waybar", "SIGUSR2");
    }
    Ok(Outcome::done(
        "waybar",
        changed,
        "accent.css + winmode block",
    ))
}

// ── kitty ──────────────────────────────────────────────────────────────────

fn kitty(ramp: Option<&Ramp>, dry: bool) -> io::Result<Outcome> {
    let conf = match ramp {
        Some(r) => format!(
            "# {HEADER}\n\
             # Full terminal palette. This is intentionally an overlay after
             # theme.conf so a wallpaper change also updates readable text,
             # not only the cursor and selection.\n\
             foreground               {}\n\
             background               {}\n\
             background_opacity       0.78\n\
             cursor                  {}\n\
             cursor_text_color       {}\n\
             url_color               {}\n\
             active_border_color     {}\n\
             active_tab_background   {}\n\
             active_tab_foreground   {}\n\
             selection_background    {}\n\
             selection_foreground    {}\n\
             mark1_background        {}\n\
             color0                  {}\n\
             color1                  {}\n\
             color2                  {}\n\
             color3                  {}\n\
             color4                  {}\n\
             color5                  {}\n\
             color6                  {}\n\
             color7                  {}\n\
             color8                  {}\n\
             color9                  {}\n\
             color10                 {}\n\
             color11                 {}\n\
             color12                 {}\n\
             color13                 {}\n\
             color14                 {}\n\
             color15                 {}\n",
            Ramp::hex(wallengine_we::accent::readable_on(r.surface)),
            Ramp::hex(r.surface),
            Ramp::hex(r.accent),
            Ramp::hex(r.on_accent),
            Ramp::hex(r.accent_hi),
            Ramp::hex(r.accent),
            Ramp::hex(r.accent),
            Ramp::hex(r.on_accent),
            Ramp::hex(r.accent_lo),
            Ramp::hex(wallengine_we::accent::readable_on(r.accent_lo)),
            Ramp::hex(r.accent),
            Ramp::hex(r.surface),
            Ramp::hex(r.accent_hi),
            Ramp::hex(r.accent),
            Ramp::hex(r.accent_hi),
            Ramp::hex(r.accent),
            Ramp::hex(r.accent_hi),
            Ramp::hex(r.accent),
            Ramp::hex(wallengine_we::accent::readable_on(r.surface)),
            Ramp::hex(r.accent_muted),
            Ramp::hex(r.accent_hi),
            Ramp::hex(r.accent),
            Ramp::hex(r.accent_hi),
            Ramp::hex(r.accent),
            Ramp::hex(r.accent_hi),
            Ramp::hex(r.accent),
            Ramp::hex(wallengine_we::accent::readable_on(r.surface)),
        ),
        None => format!("# {HEADER}\n# inactive — theme colors in use\n"),
    };
    let mut changed = write_if_changed(&home().join(".config/kitty/accent.conf"), &conf, dry)?;
    changed |= ensure_after(
        &home().join(".config/kitty/kitty.conf"),
        "include theme.conf",
        "include accent.conf",
        dry,
    )?;
    if !dry && changed && running("kitty") {
        signal("kitty", "SIGUSR1");
    }
    Ok(Outcome::done("kitty", changed, "accent.conf + include"))
}

// ── KDE / Qt ──────────────────────────────────────────────────────────────

/// Generate the desktop's standard Qt palette as a real KDE colour scheme,
/// then point KDE, Dolphin/Gwenview and qt6ct at it.  Super-T used to do this
/// only while restoring a saved theme; doing it here lets every WallStudio
/// wallpaper carry its own coherent Qt palette instead.
fn kde(ramp: Option<&Ramp>, dry: bool) -> io::Result<Outcome> {
    let Some(r) = ramp else {
        return Ok(Outcome::done("kde", false, "palette left installed"));
    };

    let text = wallengine_we::accent::readable_on(r.surface);
    let inactive = mix_rgb(text, r.surface, 0.42);
    let positive = mix_rgb(r.accent, [0.35, 0.88, 0.54], 0.45);
    let negative = mix_rgb(r.accent_hi, [0.95, 0.33, 0.42], 0.50);
    let neutral = mix_rgb(r.accent_hi, [0.95, 0.72, 0.25], 0.50);
    let colors = kde_colors(r, text, inactive, positive, negative, neutral);
    let qt6ct = qt6ct_colors(r, text, inactive);
    let mut changed = write_if_changed(
        &home().join(".local/share/color-schemes/WallStudio.colors"),
        &colors,
        dry,
    )?;
    changed |= write_if_changed(
        &home().join(".config/qt6ct/colors/wallstudio.conf"),
        &qt6ct,
        dry,
    )?;

    changed |= set_ini_values(
        &home().join(".config/kdeglobals"),
        "General",
        &[("ColorScheme", "WallStudio")],
        dry,
    )?;
    for app in ["dolphinrc", "gwenviewrc"] {
        changed |= set_ini_values(
            &home().join(".config").join(app),
            "UiSettings",
            &[("ColorScheme", "WallStudio")],
            dry,
        )?;
    }
    changed |= set_ini_values(
        &home().join(".config/qt6ct/qt6ct.conf"),
        "Appearance",
        &[
            (
                "color_scheme_path",
                &home()
                    .join(".config/qt6ct/colors/wallstudio.conf")
                    .display()
                    .to_string(),
            ),
            ("custom_palette", "true"),
        ],
        dry,
    )?;

    // Plasma broadcasts a palette change to already-running KDE apps.  On
    // Hyprland this normally has no effect, but the qt6ct file above does.
    if !dry && changed {
        let _ = Command::new("plasma-apply-colorscheme")
            .arg("WallStudio")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
    Ok(Outcome::done(
        "kde",
        changed,
        "KDE + Dolphin/Gwenview + qt6ct palette",
    ))
}

fn kde_colors(
    r: &Ramp,
    text: [f32; 3],
    inactive: [f32; 3],
    positive: [f32; 3],
    negative: [f32; 3],
    neutral: [f32; 3],
) -> String {
    let normal = kde_group(
        r.surface,
        r.surface_hi,
        r,
        text,
        inactive,
        positive,
        negative,
        neutral,
    );
    let header = kde_group(
        r.surface_hi,
        r.surface,
        r,
        text,
        inactive,
        positive,
        negative,
        neutral,
    );
    let selection = kde_group(
        r.accent_lo,
        r.accent,
        r,
        r.on_accent,
        text,
        positive,
        negative,
        neutral,
    );
    format!(
        "# {HEADER}\n[ColorEffects:Disabled]\nColor={}\nColorAmount=0\nColorEffect=0\nContrastAmount=0.65\nContrastEffect=1\nIntensityAmount=0.1\nIntensityEffect=2\n\n[ColorEffects:Inactive]\nChangeSelectionColor=true\nColor={}\nColorAmount=0.025\nColorEffect=2\nContrastAmount=0.1\nContrastEffect=2\nEnable=false\nIntensityAmount=0\nIntensityEffect=2\n\n[Colors:Button]\n{header}\n[Colors:Complementary]\n{normal}\n[Colors:Header]\n{header}\n[Colors:Header][Inactive]\n{header}\n[Colors:Selection]\n{selection}\n[Colors:Tooltip]\n{header}\n[Colors:View]\n{normal}\n[Colors:Window]\n{header}\n[General]\nColorScheme=WallStudio\nName=WallStudio (wallpaper palette)\nshadeSortColumn=true\n\n[KDE]\ncontrast=4\n\n[WM]\nactiveBackground={}\nactiveBlend={}\nactiveForeground={}\ninactiveBackground={}\ninactiveBlend={}\ninactiveForeground={}\n",
        Ramp::rgb_csv(r.surface),
        Ramp::rgb_csv(r.accent_muted),
        Ramp::rgb_csv(r.surface_hi),
        Ramp::rgb_csv(r.accent),
        Ramp::rgb_csv(text),
        Ramp::rgb_csv(r.surface),
        Ramp::rgb_csv(r.accent_muted),
        Ramp::rgb_csv(inactive),
    )
}

fn kde_group(
    background: [f32; 3],
    alternate: [f32; 3],
    r: &Ramp,
    text: [f32; 3],
    inactive: [f32; 3],
    positive: [f32; 3],
    negative: [f32; 3],
    neutral: [f32; 3],
) -> String {
    format!(
        "BackgroundAlternate={}\nBackgroundNormal={}\nDecorationFocus={}\nDecorationHover={}\nForegroundActive={}\nForegroundInactive={}\nForegroundLink={}\nForegroundNegative={}\nForegroundNeutral={}\nForegroundNormal={}\nForegroundPositive={}\nForegroundVisited={}\n\n",
        Ramp::rgb_csv(alternate), Ramp::rgb_csv(background), Ramp::rgb_csv(r.accent),
        Ramp::rgb_csv(r.accent_hi), Ramp::rgb_csv(r.accent), Ramp::rgb_csv(inactive),
        Ramp::rgb_csv(r.accent_hi), Ramp::rgb_csv(negative), Ramp::rgb_csv(neutral),
        Ramp::rgb_csv(text), Ramp::rgb_csv(positive), Ramp::rgb_csv(r.accent_lo),
    )
}

fn qt6ct_colors(r: &Ramp, text: [f32; 3], inactive: [f32; 3]) -> String {
    let hex = |c| format!("#ff{}", Ramp::hex(c).trim_start_matches('#'));
    let active = [
        text,
        r.surface_hi,
        inactive,
        r.surface_hi,
        r.surface,
        r.surface_hi,
        text,
        text,
        text,
        r.surface,
        r.surface_hi,
        r.surface,
        r.accent_lo,
        r.on_accent,
        r.accent_hi,
        r.accent,
        r.surface_hi,
        text,
        r.surface_hi,
        text,
        r.accent_muted,
        r.accent_hi,
    ];
    let inactive_colors = [
        inactive,
        r.surface,
        r.accent_muted,
        r.surface_hi,
        r.surface,
        r.surface_hi,
        inactive,
        text,
        inactive,
        r.surface,
        r.surface_hi,
        r.surface,
        r.surface_hi,
        inactive,
        inactive,
        inactive,
        r.surface_hi,
        text,
        r.surface_hi,
        text,
        r.accent_muted,
        r.surface_hi,
    ];
    format!(
        "# {HEADER}\n[ColorScheme]\nactive_colors={}\ninactive_colors={}\ndisabled_colors={}\n",
        active
            .iter()
            .map(|&c| hex(c))
            .collect::<Vec<_>>()
            .join(", "),
        inactive_colors
            .iter()
            .map(|&c| hex(c))
            .collect::<Vec<_>>()
            .join(", "),
        inactive_colors
            .iter()
            .map(|&c| hex(c))
            .collect::<Vec<_>>()
            .join(", "),
    )
}

// ── hyprland ───────────────────────────────────────────────────────────────

/// Whether `smooth::run` will really step the borders from `smooth_from` to
/// `ramp` — i.e. whether it is safe for a live-writing target to leave the
/// live push to the fade engine. False for a fade that would not move.
fn fade_will_run(smooth_from: Option<&Ramp>, ramp: Option<&Ramp>) -> bool {
    match (smooth_from, ramp) {
        (Some(from), Some(to)) => crate::smooth::step_count(from, to) > 0,
        _ => false,
    }
}

fn hyprland(ramp: Option<&Ramp>, smooth_from: Option<&Ramp>, dry: bool) -> io::Result<Outcome> {
    // hyprland.lua parses theme.conf and then this file as an overlay, so
    // there's nothing to include. accent.conf is the reload-time recovery
    // (any `hyprctl reload` re-runs the lua and would otherwise drop back to
    // the theme's colours); the live change goes straight through hyprctl,
    // which recolors without a reload (a reload flashes every border).
    let (conf, live) = match ramp {
        Some(r) => {
            let a = Ramp::hex8(r.accent, 1.0);
            let b = Ramp::hex8(r.accent_lo, 1.0);
            let inactive = Ramp::hex8(r.accent_muted, 1.0);
            let glow = Ramp::hex8(r.accent, 0.20);
            (
                format!(
                    "# {HEADER}\n\
                     general {{\n    \
                     col.active_border = rgba({a}) rgba({b}) 45deg\n    \
                     col.inactive_border = rgba({inactive})\n\
                     }}\n\n\
                     decoration {{\n    shadow {{\n        color = rgba({glow})\n    }}\n}}\n"
                ),
                Some((a, b, inactive, glow)),
            )
        }
        None => (
            format!("# {HEADER}\n# inactive — theme colors in use\n"),
            None,
        ),
    };
    // The on-disk file always carries the final value (reference + reload-time
    // recovery). Mid-fade, though, the fade engine owns the *live* border push
    // and steps it frame-by-frame — so skip the direct push here, only when a
    // fade is running.
    let changed = write_if_changed(&home().join(".config/hypr/accent.conf"), &conf, dry)?;
    let mut note = String::from("accent.conf");
    // ...but only when a fade is actually going to run. `smooth::run` bails out
    // when the accent hasn't moved (step_count == 0), so handing the live push
    // to it in that case pushes *nothing* — and Hyprland would sit on whatever
    // it last parsed until the next reload. That is exactly the boot case:
    // walld restores the session wallpaper, the accent matches state.json from
    // last session, and the borders come up un-accented until something forces
    // another apply.
    if fade_will_run(smooth_from, ramp) {
        return Ok(Outcome::done("hyprland", changed, "stepping live"));
    }
    if !dry {
        match live {
            Some((a, b, inactive, glow)) => {
                let lua = format!(
                    "hl.config({{ general = {{ col = {{ \
                       active_border = {{ colors = {{\"rgba({a})\",\"rgba({b})\"}}, angle = 45 }}, \
                       inactive_border = \"rgba({inactive})\" }} }}, \
                       decoration = {{ shadow = {{ color = \"rgba({glow})\" }} }} }})"
                );
                if hyprctl(&["repl", &lua]) {
                    note.push_str(" + live");
                } else if hyprctl(&[
                    "keyword",
                    "general:col.active_border",
                    &format!("rgba({a}) rgba({b}) 45deg"),
                ]) {
                    note.push_str(" + live (legacy)");
                } else {
                    note.push_str(" (hyprland not reachable)");
                }
            }
            None => {
                // Standing down: let Hyprland re-read the theme's own colours.
                if hyprctl(&["reload"]) {
                    note.push_str(" + reload");
                }
            }
        }
    }
    Ok(Outcome::done("hyprland", changed, note))
}

// ── rice (bash prompt) ─────────────────────────────────────────────────────

/// The themed PS1 in `~/.bashrc` (`_rice_prompt`) sources
/// `rice-prompt.colors` on every prompt; the accent overlay is sourced
/// immediately after, so its variables win while it carries colours and the
/// theme's palette shows through again the moment stand-down replaces it
/// with a stub. No signal, no reload: the very next prompt picks it up.
fn rice(ramp: Option<&Ramp>, dry: bool) -> io::Result<Outcome> {
    let conf = match ramp {
        Some(r) => format!(
            "# {HEADER}\n\
             # Sourced right after rice-prompt.colors on every bash prompt, so\n\
             # these variables override the theme's palette while the accent is\n\
             # on (wallaccent writes it; stand-down swaps it for a stub).\n\
             RICE_C_USER='{user}'\n\
             RICE_C_MUTED='{muted}'\n\
             RICE_C_DIR='{dir}'\n\
             RICE_C_GIT='{git}'\n\
             RICE_C_CHAR='{ch}'\n",
            user = rgb_semi(r.accent_hi),
            muted = rgb_semi(r.accent_muted),
            dir = rgb_semi(r.accent),
            git = rgb_semi(r.accent_lo),
            ch = rgb_semi(r.accent),
        ),
        None => format!("# {HEADER}\n# inactive — theme colors in use\n"),
    };
    let mut changed = write_if_changed(
        &home().join(".config/bash/rice-prompt-accent.colors"),
        &conf,
        dry,
    )?;
    changed |= ensure_after(
        &home().join(".config/bash/rice-prompt.colors"),
        "RICE_C_CHAR",
        "[[ -r \"${HOME}/.config/bash/rice-prompt-accent.colors\" ]] && . \"${HOME}/.config/bash/rice-prompt-accent.colors\"",
        dry,
    )?;
    Ok(Outcome::done(
        "rice",
        changed,
        "rice-prompt-accent.colors + source",
    ))
}

/// `R;G;B` decimal, semicolon-separated — the truecolor form
/// `rice-prompt.colors` uses (compare with `Ramp::rgb_csv`'s CSS form).
fn rgb_semi(c: [f32; 3]) -> String {
    format!(
        "{r};{g};{b}",
        r = (c[0].clamp(0.0, 1.0) * 255.0).round() as u8,
        g = (c[1].clamp(0.0, 1.0) * 255.0).round() as u8,
        b = (c[2].clamp(0.0, 1.0) * 255.0).round() as u8,
    )
}

// ── mako ───────────────────────────────────────────────────────────────────

fn mako(ramp: Option<&Ramp>, dry: bool) -> io::Result<Outcome> {
    let body = match ramp {
        Some(r) => format!(
            "border-color=#{}\nprogress-color=over #{}\n[urgency=critical]\nborder-color=#{}\n",
            Ramp::hex8(r.accent, 0.93),
            Ramp::hex8(r.accent_lo, 1.0),
            Ramp::hex8(r.accent_hi, 1.0),
        ),
        None => String::new(),
    };
    let path = home().join(".config/mako/config");
    let changed = patch_block(
        &path,
        &format!("# {BEGIN}"),
        &format!("# {END}"),
        &body,
        Anchor::End,
        dry,
    )?;
    if !dry && changed {
        let _ = Command::new("makoctl")
            .arg("reload")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
    Ok(Outcome::done("mako", changed, "config block"))
}

// ── rofi ───────────────────────────────────────────────────────────────────

fn rofi(ramp: Option<&Ramp>, dry: bool) -> io::Result<Outcome> {
    let rasi = match ramp {
        Some(r) => format!(
            "/* {HEADER} */\n* {{\n  \
             accent:  {};\n  \
             accent2: {};\n  \
             urgent:  {};\n  \
             border:  rgba({}, 0.35);\n}}\n",
            Ramp::hex(r.accent),
            Ramp::hex(r.accent_lo),
            Ramp::hex(r.accent_hi),
            Ramp::rgb_csv(r.accent),
        ),
        None => format!("/* {HEADER} */\n* {{ }}\n"),
    };
    let mut changed = write_if_changed(&home().join(".config/rofi/accent.rasi"), &rasi, dry)?;
    // Must land after `@theme`, which resets the `*` block.
    changed |= ensure_after(
        &home().join(".config/rofi/config.rasi"),
        "@theme ",
        "@import \"~/.config/rofi/accent.rasi\"",
        dry,
    )?;
    // rofi reads its config per launch — nothing to reload.
    Ok(Outcome::done("rofi", changed, "accent.rasi + @import"))
}

// ── fastfetch ──────────────────────────────────────────────────────────────

/// Recolor the fastfetch rice: rewrite every truecolor escape in its config
/// (`38;2;R;G;B`, with or without an ESC[ prefix) to the accent ramp.
///
/// JSONC has no include and no end-of-file override, so this is a patcher
/// target like mako — but its markers are *invisible to fastfetch*: plain
/// comment lines in the body, no marker text in the file itself. That way
/// `theme snapshot` can capture a recolor'd rice and `theme apply` can
/// hand it straight back; a marker inside would break strict JSONC parsing.
///
/// Only colours are rewritten; the file's layout, comments and non-colour
/// values (module order, formats, logo choice) stay exactly where they were.
fn fastfetch(ramp: Option<&Ramp>, smooth_from: Option<&Ramp>, dry: bool) -> io::Result<Outcome> {
    let path = home().join(".config/fastfetch/config.jsonc");
    let _ = smooth_from; // fastfetch reads its config per run — always write now
    let changed = match ramp {
        Some(r) => {
            let Some(text) = std::fs::read_to_string(&path).ok() else {
                // No fastfetch config → nothing to recolor (not an error).
                return Ok(Outcome::done("fastfetch", false, "no config.jsonc"));
            };
            let new = recolor_jsonc(&text, r);
            write_if_changed(&path, &new, dry)?
        }
        // Standing down can't restore the theme's colours on its own — the
        // rice's palette lives inline in this one file and the next
        // `theme apply` puts them back. Leave what's there.
        None => false,
    };
    // fastfetch reads its config on every run — nothing to reload.
    Ok(Outcome::done("fastfetch", changed, "config.jsonc colors"))
}

/// Rewrite fastfetch truecolor escapes in `text` to ramp colours, preserving
/// everything else byte for byte. Exposed for tests; `fastfetch` uses it.
pub fn recolor_jsonc(text: &str, r: &Ramp) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while !rest.is_empty() {
        // A truecolor run starts with `38;2;` whether or not an ESC[ (in its
        // \\u001b JSON escape form) sits right before it.
        if let Some(n) = rest.find("38;2;") {
            let (head, tail) = rest.split_at(n);
            // A digit before it means this is mid-number, not a colour.
            if head.chars().next_back().is_some_and(|c| c.is_ascii_digit()) {
                out.push_str(head);
                out.push_str("38;2;");
                rest = &tail["38;2;".len()..];
                continue;
            }
            out.push_str(head);
            let len = skip_truecolor_csv(tail.as_bytes());
            if len > 0 {
                out.push_str(&csv(&ramp_color_for(&tail[..len], r)));
                rest = &tail[len..];
                continue;
            }
            // Looked like one but wasn't — copy the marker verbatim.
            out.push_str("38;2;");
            rest = &tail["38;2;".len()..];
            continue;
        }
        out.push_str(rest);
        break;
    }
    out
}

/// Length of `38;2;R;G;B` at the front of `bytes` (0 when it doesn't match).
fn skip_truecolor_csv(bytes: &[u8]) -> usize {
    let mut n = 0usize;
    let mut count = 0usize;
    let mut digits = false;
    while n < bytes.len() && count < 5 {
        match bytes[n] {
            b'0'..=b'9' => {
                digits = true;
                n += 1;
            }
            b';' if digits && count < 4 => {
                count += 1;
                digits = false;
                n += 1;
            }
            _ => break,
        }
    }
    if count == 4 && digits {
        n
    } else {
        0
    }
}

/// Which ramp shade an occurrence carries, judged by what the *original* rice
/// used there. Roles: bright key/title/logo → accent; the darker partner
/// (host, keys, second logo colour) → accent_lo; body output → light neutral;
/// "at" / separator → accent_muted.
fn ramp_color_for(occurrence: &str, r: &Ramp) -> [f32; 3] {
    let rgb = |s: &str| -> Option<[f32; 3]> {
        let s = s.strip_prefix("\\u001b[").unwrap_or(s);
        let rest = s.strip_prefix("38;2;")?;
        let rest = rest.strip_suffix('m').unwrap_or(rest);
        let mut ch = rest.split(';');
        Some([
            ch.next()?.parse::<u8>().ok()? as f32 / 255.0,
            ch.next()?.parse::<u8>().ok()? as f32 / 255.0,
            ch.next()?.parse::<u8>().ok()? as f32 / 255.0,
        ])
    };
    let Some(c) = rgb(occurrence) else {
        return r.accent;
    };
    let (_h, s, v) = wallengine_we::rgb_to_hsv(c[0], c[1], c[2]);
    let luma = wallengine_we::accent::relative_luminance(c);
    // Dim / muted roles: greyish, or dark and low-chroma ("at", separators).
    if (s < 0.25 && v < 0.85) || (luma < 0.12 && s < 0.5) {
        return r.accent_muted;
    }
    // Body text: light, low chroma → keep it a light neutral so the keys
    // stay the pop of colour.
    if v > 0.72 && s < 0.35 {
        return mix_rgb([1.0, 1.0, 1.0], r.accent, 0.10);
    }
    // Chromatic pair: the luminous member carries the accent, the darker one
    // (secondary logo colour, keys, host) gets the deep companion. HSV value
    // can't tell these apart (183;148;246 and 124;92;191 are both "bright");
    // luminance does. 0.18 sits below accent's guaranteed floor (contrast
    // 4.6 against dark chrome ⇒ luma ≥ ~0.20) and above accent_lo's ceiling,
    // so a second pass re-classifies every slot as itself.
    if luma >= 0.18 {
        r.accent
    } else {
        r.accent_lo
    }
}

fn mix_rgb(a: [f32; 3], b: [f32; 3], t: f32) -> [f32; 3] {
    [
        a[0] + (b[0] - a[0]) * t,
        a[1] + (b[1] - a[1]) * t,
        a[2] + (b[2] - a[2]) * t,
    ]
}

fn csv(c: &[f32; 3]) -> String {
    format!("38;2;{}", Ramp::rgb_csv(*c).replace(", ", ";"))
}

// ── gtk ────────────────────────────────────────────────────────────────────

fn gtk(ramp: Option<&Ramp>, dry: bool) -> io::Result<Outcome> {
    let css = match ramp {
        Some(r) => {
            let text = wallengine_we::accent::readable_on(r.surface);
            format!(
                "/* {HEADER} */\n\
             @define-color theme_bg_color {};\n\
             @define-color theme_base_color {};\n\
             @define-color theme_fg_color {};\n\
             @define-color theme_text_color {};\n\
             @define-color window_bg_color {};\n\
             @define-color window_fg_color {};\n\
             @define-color view_bg_color {};\n\
             @define-color view_fg_color {};\n\
             @define-color borders {};\n\
             @define-color accent_color {};\n\
             @define-color accent_bg_color {};\n\
             @define-color accent_fg_color {};\n\
             @define-color theme_selected_bg_color {};\n\
             @define-color theme_selected_fg_color {};\n",
                Ramp::hex(r.surface_hi),
                Ramp::hex(r.surface),
                Ramp::hex(text),
                Ramp::hex(text),
                Ramp::hex(r.surface_hi),
                Ramp::hex(text),
                Ramp::hex(r.surface),
                Ramp::hex(text),
                Ramp::hex(r.accent_muted),
                Ramp::hex(r.accent),
                Ramp::hex(r.accent),
                Ramp::hex(r.on_accent),
                Ramp::hex(r.accent),
                Ramp::hex(r.on_accent),
            )
        }
        None => format!("/* {HEADER} */\n"),
    };
    let mut changed = false;
    for ver in ["gtk-3.0", "gtk-4.0"] {
        changed |= write_if_changed(&home().join(format!(".config/{ver}/accent.css")), &css, dry)?;
        changed |= ensure_after(
            &home().join(format!(".config/{ver}/gtk.css")),
            "", // no anchor: append at the end so it wins
            "@import url(\"accent.css\");",
            dry,
        )?;
    }
    Ok(Outcome::done(
        "gtk",
        changed,
        "accent.css + @import (restart apps)",
    ))
}

// ── file plumbing ──────────────────────────────────────────────────────────

/// Write `content` only when it differs. Returns whether the file changed.
pub fn write_if_changed(path: &Path, content: &str, dry: bool) -> io::Result<bool> {
    if std::fs::read_to_string(path).is_ok_and(|old| old == content) {
        return Ok(false);
    }
    if dry {
        return Ok(true);
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    Ok(true)
}

/// Set selected keys in a KDE/Qt INI file without disturbing its unrelated
/// application preferences. Unlike shelling out to `kwriteconfig6`, this also
/// works in a minimal Hyprland installation and is easy to dry-run.
fn set_ini_values(
    path: &Path,
    section: &str,
    values: &[(&str, &str)],
    dry: bool,
) -> io::Result<bool> {
    let text = std::fs::read_to_string(path).unwrap_or_default();
    let header = format!("[{section}]");
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    let start = lines.iter().position(|line| line.trim() == header);
    if start.is_none() {
        if !lines.is_empty() && lines.last().is_some_and(|line| !line.is_empty()) {
            lines.push(String::new());
        }
        lines.push(header);
        lines.extend(values.iter().map(|(key, value)| format!("{key}={value}")));
    } else {
        let start = start.unwrap();
        let end = lines[start + 1..]
            .iter()
            .position(|line| line.trim().starts_with('[') && line.trim().ends_with(']'))
            .map(|i| start + 1 + i)
            .unwrap_or(lines.len());
        let mut seen = vec![false; values.len()];
        for line in &mut lines[start + 1..end] {
            let Some((key, _)) = line.split_once('=') else {
                continue;
            };
            if let Some((index, (_, value))) = values
                .iter()
                .enumerate()
                .find(|(_, (wanted, _))| key.trim() == *wanted)
            {
                *line = format!("{}={value}", values[index].0);
                seen[index] = true;
            }
        }
        let missing: Vec<String> = values
            .iter()
            .enumerate()
            .filter(|(index, _)| !seen[*index])
            .map(|(_, (key, value))| format!("{key}={value}"))
            .collect();
        lines.splice(end..end, missing);
    }
    let mut new = lines.join("\n");
    new.push('\n');
    write_if_changed(path, &new, dry)
}

/// Ensure `line` appears in `host`, directly after the first line containing
/// `after` (or appended when `after` is empty / missing). Idempotent.
///
/// Missing host files are left alone: a config that doesn't exist isn't ours
/// to create.
pub fn ensure_after(host: &Path, after: &str, line: &str, dry: bool) -> io::Result<bool> {
    let Ok(text) = std::fs::read_to_string(host) else {
        return Ok(false);
    };
    if text.lines().any(|l| l.trim() == line.trim()) {
        return Ok(false);
    }
    if dry {
        return Ok(true);
    }
    let mut out: Vec<String> = Vec::new();
    let mut placed = false;
    for l in text.lines() {
        out.push(l.to_string());
        if !placed && !after.is_empty() && l.contains(after) {
            out.push(line.to_string());
            placed = true;
        }
    }
    if !placed {
        out.push(line.to_string());
    }
    let mut joined = out.join("\n");
    joined.push('\n');
    std::fs::write(host, joined)?;
    Ok(true)
}

/// Where a generated block goes when it isn't already in the file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Anchor<'a> {
    /// Append at the end of the file.
    End,
    /// Insert directly after the last line starting with this prefix.
    ///
    /// Needed for GTK CSS: `@define-color` is resolved in source order, so an
    /// override has to sit after the theme's palette but before the rules that
    /// read it. A block at the end of the file would simply never apply.
    AfterLastLineStartingWith(&'a str),
}

/// Replace this tool's marker block in `path`, inserting it at `anchor` when
/// absent. An empty `body` removes the block, restoring the original file.
pub fn patch_block(
    path: &Path,
    begin: &str,
    end: &str,
    body: &str,
    anchor: Anchor<'_>,
    dry: bool,
) -> io::Result<bool> {
    let Ok(text) = std::fs::read_to_string(path) else {
        return Ok(false);
    };

    // Strip any existing block first, so rewrites replace instead of stack.
    let mut kept: Vec<String> = Vec::new();
    let mut inside = false;
    for l in text.lines() {
        if l.trim() == begin {
            inside = true;
            continue;
        }
        if l.trim() == end {
            inside = false;
            continue;
        }
        if !inside {
            kept.push(l.to_string());
        }
    }

    let out = if body.trim().is_empty() {
        while kept.last().is_some_and(|l| l.trim().is_empty()) {
            kept.pop();
        }
        let mut o = kept.join("\n");
        o.push('\n');
        o
    } else {
        let block: Vec<String> = std::iter::once(begin.to_string())
            .chain(body.trim_end().lines().map(str::to_string))
            .chain(std::iter::once(end.to_string()))
            .collect();
        let at = match anchor {
            Anchor::End => {
                while kept.last().is_some_and(|l| l.trim().is_empty()) {
                    kept.pop();
                }
                kept.push(String::new());
                kept.len()
            }
            Anchor::AfterLastLineStartingWith(prefix) => kept
                .iter()
                .rposition(|l| l.trim_start().starts_with(prefix))
                .map(|i| i + 1)
                .unwrap_or(kept.len()),
        };
        let mut o: Vec<String> = Vec::with_capacity(kept.len() + block.len());
        o.extend_from_slice(&kept[..at]);
        o.extend(block);
        o.extend_from_slice(&kept[at..]);
        let mut joined = o.join("\n");
        joined.push('\n');
        joined
    };

    if out == text {
        return Ok(false);
    }
    if dry {
        return Ok(true);
    }
    std::fs::write(path, out)?;
    Ok(true)
}

/// Drop every occurrence of `line` from `host` (used to clean up an include
/// this tool added before it knew better).
pub fn remove_line(host: &Path, line: &str, dry: bool) -> io::Result<bool> {
    let Ok(text) = std::fs::read_to_string(host) else {
        return Ok(false);
    };
    if !text.lines().any(|l| l.trim() == line.trim()) {
        return Ok(false);
    }
    if dry {
        return Ok(true);
    }
    let mut out: String = text
        .lines()
        .filter(|l| l.trim() != line.trim())
        .collect::<Vec<_>>()
        .join("\n");
    out.push('\n');
    std::fs::write(host, out)?;
    Ok(true)
}

fn running(name: &str) -> bool {
    Command::new("pgrep")
        .args(["-x", name])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

fn signal(name: &str, sig: &str) {
    let _ = Command::new("pkill")
        .args([&format!("-{sig}"), "-x", name])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
}

fn hyprctl(args: &[&str]) -> bool {
    Command::new("hyprctl")
        .args(args)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

/// Path of a generated file, for `status`.
pub fn generated_files() -> Vec<PathBuf> {
    [
        ".config/waybar/accent.css",
        ".config/kitty/accent.conf",
        ".config/hypr/accent.conf",
        ".config/rofi/accent.rasi",
        ".config/gtk-3.0/accent.css",
        ".config/gtk-4.0/accent.css",
        ".config/bash/rice-prompt-accent.colors",
    ]
    .iter()
    .map(|p| home().join(p))
    .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp(tag: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!(
            "wallaccent-t-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    // Booting with the same wallpaper as last session: the ramp matches
    // state.json, so the fade has nothing to step. The hyprland target must
    // then push live itself — a skipped push leaves the desktop on whatever
    // colours Hyprland last parsed until the next reload.
    #[test]
    fn unmoved_accent_does_not_hand_the_live_push_to_the_fade() {
        let a = Ramp::derive([0.23, 0.56, 0.62], 1.0);
        let b = Ramp::derive([1.0, 0.12, 0.24], 1.0);
        assert!(
            !fade_will_run(Some(&a), Some(&a)),
            "identical ramps must not claim a fade"
        );
        assert!(
            fade_will_run(Some(&a), Some(&b)),
            "a real colour move still fades"
        );
        // No previous state (first ever run) and stand-down both push directly.
        assert!(!fade_will_run(None, Some(&b)));
        assert!(!fade_will_run(Some(&a), None));
    }

    #[test]
    fn rgb_semi_is_truecolor_semicolons() {
        assert_eq!(rgb_semi([1.0, 0.0, 0.0]), "255;0;0");
        assert_eq!(
            rgb_semi([242.0 / 255.0, 47.0 / 255.0, 91.0 / 255.0]),
            "242;47;91"
        );
        assert_eq!(rgb_semi([-0.1, 1.7, 0.5]), "0;255;128"); // clamped
    }

    #[test]
    fn write_if_changed_is_idempotent() {
        let d = tmp("w");
        let f = d.join("a.css");
        assert!(write_if_changed(&f, "x\n", false).unwrap());
        assert!(!write_if_changed(&f, "x\n", false).unwrap());
        assert!(write_if_changed(&f, "y\n", false).unwrap());
        assert_eq!(std::fs::read_to_string(&f).unwrap(), "y\n");
        // Dry runs report the change without touching disk.
        assert!(write_if_changed(&f, "z\n", true).unwrap());
        assert_eq!(std::fs::read_to_string(&f).unwrap(), "y\n");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn include_lands_directly_after_the_theme_import() {
        let d = tmp("i");
        let f = d.join("style.css");
        std::fs::write(
            &f,
            "@import \"theme.css\";\n@import \"styles/fonts.css\";\n",
        )
        .unwrap();
        assert!(ensure_after(
            &f,
            "@import \"theme.css\";",
            "@import \"accent.css\";",
            false
        )
        .unwrap());
        assert_eq!(
            std::fs::read_to_string(&f).unwrap(),
            "@import \"theme.css\";\n@import \"accent.css\";\n@import \"styles/fonts.css\";\n"
        );
        // Second run is a no-op — this runs after every theme apply.
        assert!(!ensure_after(
            &f,
            "@import \"theme.css\";",
            "@import \"accent.css\";",
            false
        )
        .unwrap());
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn include_appends_when_the_anchor_is_missing() {
        let d = tmp("i2");
        let f = d.join("kitty.conf");
        std::fs::write(&f, "font_size 11\n").unwrap();
        assert!(ensure_after(&f, "include theme.conf", "include accent.conf", false).unwrap());
        assert_eq!(
            std::fs::read_to_string(&f).unwrap(),
            "font_size 11\ninclude accent.conf\n"
        );
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn missing_host_file_is_left_alone() {
        let d = tmp("i3");
        let f = d.join("nope.conf");
        assert!(!ensure_after(&f, "x", "y", false).unwrap());
        assert!(!f.exists());
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn block_round_trips_without_growing() {
        let d = tmp("b");
        let f = d.join("config");
        let original = "max-history=50\nfont=Mono 10\n";
        std::fs::write(&f, original).unwrap();
        let (b, e) = ("# wallaccent:begin", "# wallaccent:end");

        assert!(patch_block(&f, b, e, "border-color=#ff0000ff\n", Anchor::End, false).unwrap());
        let once = std::fs::read_to_string(&f).unwrap();
        assert!(once.starts_with(original.trim_end()));
        assert!(once.contains("border-color=#ff0000ff"));

        // Rewriting must replace, not stack.
        assert!(patch_block(&f, b, e, "border-color=#00ff00ff\n", Anchor::End, false).unwrap());
        let twice = std::fs::read_to_string(&f).unwrap();
        assert_eq!(twice.matches("wallaccent:begin").count(), 1);
        assert!(!twice.contains("ff0000"));
        assert_eq!(twice.len(), once.len());

        // Same colour again → no write.
        assert!(!patch_block(&f, b, e, "border-color=#00ff00ff\n", Anchor::End, false).unwrap());

        // Empty body removes the block and restores the original file.
        assert!(patch_block(&f, b, e, "", Anchor::End, false).unwrap());
        assert_eq!(std::fs::read_to_string(&f).unwrap(), original);
        let _ = std::fs::remove_dir_all(&d);
    }

    /// GTK resolves `@define-color` in source order, so the override has to
    /// land after the theme's palette but before the rules that read it.
    #[test]
    fn css_block_lands_after_the_palette_not_at_the_end() {
        let d = tmp("css");
        let f = d.join("style.css");
        std::fs::write(
            &f,
            "/* header */\n\
             @define-color win-bg #000000;\n\
             @define-color win-accent #ff1e3c;\n\
             \n\
             window#waybar { background: @win-bg; }\n\
             #clock { color: @win-accent; }\n",
        )
        .unwrap();
        let (b, e) = ("/* wallaccent:begin */", "/* wallaccent:end */");
        assert!(patch_block(
            &f,
            b,
            e,
            "@define-color win-accent #4979EB;\n",
            Anchor::AfterLastLineStartingWith("@define-color"),
            false
        )
        .unwrap());

        let out = std::fs::read_to_string(&f).unwrap();
        let block = out.find("wallaccent:begin").unwrap();
        let rules = out.find("window#waybar").unwrap();
        let palette = out.find("@define-color win-bg").unwrap();
        assert!(
            palette < block && block < rules,
            "block is in the wrong place:\n{out}"
        );

        // Rewrite keeps it in the same place and doesn't duplicate.
        assert!(patch_block(
            &f,
            b,
            e,
            "@define-color win-accent #00FF00;\n",
            Anchor::AfterLastLineStartingWith("@define-color"),
            false
        )
        .unwrap());
        let out2 = std::fs::read_to_string(&f).unwrap();
        assert_eq!(out2.matches("wallaccent:begin").count(), 1);
        assert!(out2.find("wallaccent:begin").unwrap() < out2.find("window#waybar").unwrap());
        assert!(!out2.contains("4979EB"));

        // And removing it restores rule order untouched.
        assert!(patch_block(
            &f,
            b,
            e,
            "",
            Anchor::AfterLastLineStartingWith("@define-color"),
            false
        )
        .unwrap());
        assert!(!std::fs::read_to_string(&f).unwrap().contains("wallaccent"));
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn remove_line_is_idempotent() {
        let d = tmp("rm");
        let f = d.join("style.css");
        std::fs::write(&f, "a\n@import \"accent.css\";\nb\n").unwrap();
        assert!(remove_line(&f, "@import \"accent.css\";", false).unwrap());
        assert_eq!(std::fs::read_to_string(&f).unwrap(), "a\nb\n");
        assert!(!remove_line(&f, "@import \"accent.css\";", false).unwrap());
        let _ = std::fs::remove_dir_all(&d);
    }

    /// The rice's palette sits inline in one JSONC file: recoloring must map
    /// each occurrence's *role* (accent / secondary / output / dim) to the
    /// right ramp shade, leave every other byte alone, and stay stable when
    /// run twice (the next wallpaper switch starts from our own colours).
    #[test]
    fn fastfetch_recolor_maps_roles_and_is_stable() {
        let sample = "{\n\
             \u{20}// comment with 「 天上天下 」 art\n\
             \"logo\": { \"color\": { \"1\": \"38;2;183;148;246\", \"2\": \"38;2;124;92;191\" } },\n\
             \"display\": { \"color\": {\n\
             \"title\": \"38;2;183;148;246\", \"keys\": \"38;2;124;92;191\",\n\
             \"output\": \"38;2;200;190;220\" } },\n\
             \"modules\": [\n\
             { \"color\": { \"user\": \"38;2;183;148;246\", \"at\": \"38;2;90;84;104\", \"host\": \"38;2;124;92;191\" } },\n\
             { \"outputColor\": \"38;2;90;84;104\", \"keyColor\": \"38;2;183;148;246\" },\n\
             { \"format\": \"  \\u001b[38;2;183;148;246m「 唯我独尊 」\\u001b[0m\" }\n\
             ]\n\
             }\n";
        let r = Ramp::derive(wallengine_we::accent::from_hex("#4C989E").unwrap(), 1.0);
        let accent = csv(&r.accent);
        let lo = csv(&r.accent_lo);
        let muted = csv(&r.accent_muted);

        let out = recolor_jsonc(sample, &r);
        // logo "1", display title, user, keyColor, custom format line.
        assert_eq!(out.matches(&accent).count(), 5, "accent role count");
        // The deep companion replaced the darker purple everywhere.
        assert!(out.contains(&format!("\"2\": \"{lo}\"")));
        assert!(out.contains(&format!("\"host\": \"{lo}\"")));
        assert!(
            out.contains(&format!("\"keys\":  \"{lo}\""))
                || out.contains(&format!("\"keys\": \"{lo}\""))
        );
        // Dim greys became accent_muted; light body text a light neutral.
        assert!(!out.contains("38;2;90;84;104"), "dim colour survived");
        assert!(out.contains(&muted));
        assert!(!out.contains("38;2;200;190;220"), "output colour survived");
        // Structure and art untouched.
        assert!(out.contains("「 唯我独尊 」"));
        assert!(out.contains("// comment with 「 天上天下 」 art"));
        assert!(out.contains("\\u001b["), "escape prefix rewritten intact");
        assert!(out.contains("\\u001b[0m"));
        // Still valid JSON once the JSONC comment is gone (no markers, no
        // stray bytes introduced by the rewrite).
        let strict = out
            .lines()
            .filter(|l| !l.trim_start().starts_with("//"))
            .collect::<Vec<_>>()
            .join("\n");
        let v: serde_json::Value = serde_json::from_str(&strict).unwrap();
        assert!(v.get("modules").is_some());

        // A second pass must change nothing.
        assert_eq!(recolor_jsonc(&out, &r), out);
    }

    #[test]
    fn recolor_ignores_numbers_that_only_look_like_colors() {
        let r = Ramp::derive([0.4, 0.2, 0.8], 1.0);
        // `138;2;…` and a bare `38;2` with too few channels are not colours.
        let s = "\"a\": 138;2;10;20;30, \"b\": \"38;2\"";
        assert_eq!(recolor_jsonc(s, &r), s);
    }

    #[test]
    fn every_target_name_is_handled() {
        for t in ALL {
            let out = apply(t, None, None, true).unwrap();
            assert_ne!(out.name, "unknown", "target {t} is not wired up");
        }
        assert_eq!(apply("bogus", None, None, true).unwrap().name, "unknown");
    }

    #[test]
    fn defaults_are_a_subset_of_all() {
        for t in DEFAULT_ON {
            assert!(ALL.contains(t), "{t} missing from ALL");
        }
    }

    #[test]
    fn ini_writer_changes_only_the_requested_palette_keys() {
        let d = tmp("ini");
        let f = d.join("dolphinrc");
        std::fs::write(
            &f,
            "[General]\nViewPropsTimestamp=now\n\n[UiSettings]\nColorScheme=Arctic\nOther=true\n",
        )
        .unwrap();
        assert!(set_ini_values(&f, "UiSettings", &[("ColorScheme", "WallStudio")], false).unwrap());
        assert_eq!(
            std::fs::read_to_string(&f).unwrap(),
            "[General]\nViewPropsTimestamp=now\n\n[UiSettings]\nColorScheme=WallStudio\nOther=true\n"
        );
        assert!(
            !set_ini_values(&f, "UiSettings", &[("ColorScheme", "WallStudio")], false).unwrap()
        );
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn kde_palette_is_complete_and_wallpaper_derived() {
        let r = Ramp::derive([0.12, 0.64, 0.91], 1.0);
        let text = wallengine_we::accent::readable_on(r.surface);
        let out = kde_colors(
            &r,
            text,
            mix_rgb(text, r.surface, 0.42),
            [0.35, 0.88, 0.54],
            [0.95, 0.33, 0.42],
            [0.95, 0.72, 0.25],
        );
        assert!(out.contains("[Colors:Window]"));
        assert!(out.contains("[Colors:Selection]"));
        assert!(out.contains("ColorScheme=WallStudio"));
        assert!(out.contains(&Ramp::rgb_csv(r.accent)));
    }
}
